controller_frequency: 10.0
TrajectoryPlannerROS:
  max_vel_x: 0.35
  min_vel_x: 0.10
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.7
  acc_lim_th: 0.55
  acc_lim_x: 0.30
  acc_lim_y: 0.00

  holonomic_robot: false
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15

  meter_scoring: true
  goal_distance_bias: 0.16
  path_distance_bias: 0.12
  occdist_scale: 0.01
  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 10
  vtheta_samples: 30
  dwa: false

