# The remove_prefix is important - it corresponds to the name of
# the node that is automatically prefixed to cpp diagnostic task
# names. In our case it's the mobile base nodelet manager name.
# Android is not expecting this, so we need to remove it.

pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  power:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Power System'
    timeout: 5.0
    contains: ['Battery', 'Laptop Battery', 'laptop_battery_1', 'laptop_battery_2']
    remove_prefix: mobile_base_nodelet_manager
  zerg_odom:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Zerg'
    timeout: 5.0
    num_items: 2
    startswith: 'odom'
  laser:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Laser'
    timeout: 5.0
    num_items: 2
    find_and_remove_prefix: base_laser_node
  joystick:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Joystick'
    timeout: 5.0
    contains: ['Joystick Driver Status']
    remove_prefix: joystick

#  nodes:
#    type: diagnostic_aggregator/GenericAnalyzer
#    path: 'Nodes'
#    timeout: 5.0
#    contains: ['Node']
